import { Inter } from 'next/font/google';
import './globals.css';
import SparklesIcon from '@/components/SparklesIcon';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={'bg-gradient-to-b from-black/100 to-black/50 text-white min-h-screen'}>
        <main className="p-4 max-w-2xl mx-auto">
          <header className="flex justify-between my-8">
            <Link href="/" className="flex gap-1">
              <SparklesIcon />
              <span>EpicCaptions</span>
            </Link>
            <nav className="flex gap-6 text-white/80">
              <Link href="/">Home</Link>
              <Link href="/pricing">Pricing</Link>
              <a href="mailto:contact@epiccaptions.com">Contact</a>
            </nav>
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
